{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "a59d4fc8-c7f4-4627-9777-3be21f1b1c58",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "# British Airways Internship - Task 1\n",
    "\n",
    "## BA Customer Review Analysis\n",
    "\n",
    "### Overview\n",
    "\n",
    "Welcome to Task 1 of the British Airways Internship! 🛫 This project focuses on analyzing customer reviews of British Airways (BA) gathered from [skytrax](https://www.airlinequality.com/airline-reviews/british-airways). From sentiment analysis to topic modeling, delve into the depths of customer feedback to gain insights into passenger experiences and satisfaction levels.\n",
    "\n",
    "### 🔍 Code Overview\n",
    "\n",
    "#### 1. Web Scraping\n",
    "\n",
    "The code scrapes customer reviews of British Airways from airlinequality.com, collecting various attributes such as aircraft type, traveler type, seat type, country of residence, route, recommended status, overall rating, and more.\n",
    "\n",
    "#### 2. Cleaning & Preprocessing\n",
    "\n",
    "After scraping the data, the code performs cleaning and preprocessing tasks, including handling missing values, converting data types, removing duplicates, and splitting the 'route' column into 'from' and 'to' destinations.\n",
    "\n",
    "#### 3. Exploratory Data Analysis (EDA)\n",
    "\n",
    "The EDA section provides insights into the dataset through descriptive statistics, visualization of data distributions, correlation analysis, trend analysis, and more. Key visualizations include histograms, box plots, heatmaps, trend plots, and sentiment analysis.\n",
    "\n",
    "#### 4. Sentiment Analysis\n",
    "\n",
    "Sentiment analysis is conducted to assess the polarity of customer reviews, categorizing them as positive, neutral, or negative. The code calculates sentiment scores using TextBlob and visualizes sentiment distributions over time.\n",
    "\n",
    "#### 5. WordCloud of Reviews\n",
    "\n",
    "Word clouds are generated to visually represent the most frequent words in customer reviews. Separate word clouds are created for all reviews, positive reviews, and negative reviews, offering a glimpse into the most commonly mentioned aspects.\n",
    "\n",
    "#### 6. Topic Modeling\n",
    "\n",
    "The code implements topic modeling using Non-negative Matrix Factorization (NMF) to identify prevalent topics in customer reviews. Top words for each topic are displayed, and the distribution of reviews among topics is visualized.\n",
    "\n",
    "#### 7. Analysis of Reviews After Mid-2022\n",
    "\n",
    "A specific analysis is performed on negative reviews posted after mid-2022, exploring topics such as connecting flight hassles, business class woes, customer service critique, luggage woes and delays, and culinary and service disappointments.\n",
    "\n",
    "### 💻 How to Use\n",
    "\n",
    "1. Clone the Repository.\n",
    "2. Navigate to the Project Directory.\n",
    "3. Explore the Task 2 Notebook.\n",
    "4. Run the Notebook Cells.\n",
    "\n",
    "\n",
    "### 🛠️ Dependencies\n",
    "\n",
    "#### Required Libraries:\n",
    "\n",
    "- requests\n",
    "- BeautifulSoup\n",
    "- pandas\n",
    "- collections\n",
    "- numpy\n",
    "- seaborn\n",
    "- matplotlib\n",
    "- textblob\n",
    "- wordcloud\n",
    "- time\n",
    "- gensim\n",
    "- nltk\n",
    "- sklearn\n",
    "- plotly\n",
    "- PIL\n",
    "\n",
    "### 📝 Note\n",
    "\n",
    "Please refrain from directly copying the internship task code for commercial purposes. This repository is for educational purposes only. Use the code wisely and responsibly, and strive to understand the concepts and methodologies behind the analysis.\n",
    "\n",
    "### Conclusion\n",
    "\n",
    "The BA Customer Review Analysis offers valuable insights into customer sentiments and preferences regarding British Airways services. By understanding the key drivers of customer satisfaction and dissatisfaction, BA can make informed decisions to improve its offerings and enhance the overall passenger experience.\n",
    "\n",
    "---\n",
    "\n",
    "Feel free to explore the code and analysis further to gain deeper insights into BA customer feedback! ✈️📊"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
