{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "0fb94e88-4f47-4309-a425-a0b00134b55a",
   "metadata": {},
   "source": [
    "---\n",
    "\n",
    "# British Airways Internship - Task 2\n",
    "\n",
    "## BA Customer Booking Prediction\n",
    "\n",
    "### Overview\n",
    "\n",
    "Welcome to Task 2 of the British Airways Internship! In this task, we delve into the fascinating world of predictive modeling to understand customer booking behavior. By leveraging advanced machine learning techniques, we aim to uncover the key factors influencing booking decisions, empowering British Airways to tailor its services and offerings effectively.\n",
    "\n",
    "### 🔍 Code Overview\n",
    "\n",
    "#### 1. Importing Libraries\n",
    "\n",
    "We start by importing essential libraries for data manipulation, visualization, and machine learning.\n",
    "\n",
    "#### 2. Importing Dataset\n",
    "\n",
    "The dataset (`customer_booking.csv`) is loaded into a Pandas DataFrame for comprehensive analysis.\n",
    "\n",
    "#### 3. Exploratory Data Analysis (EDA)\n",
    "\n",
    "We dive into exploratory data analysis to gain insights into the dataset, visualize key features, and understand their distributions.\n",
    "\n",
    "#### 4. Pre-processing\n",
    "\n",
    "Prepare the dataset for modeling by handling categorical variables, exploring unique values, and splitting the data into training and testing sets.\n",
    "\n",
    "#### 5. Model Training - CatBoost\n",
    "\n",
    "Train a powerful CatBoostClassifier, evaluate its performance, and visualize key metrics and confusion matrices.\n",
    "\n",
    "#### 6. Model Training - XGBoost\n",
    "\n",
    "Utilize XGBoost to train a robust model with different configurations, including default settings, validation sets, and hyperparameter tuning.\n",
    "\n",
    "#### 7. Evaluation Metrics\n",
    "\n",
    "Assess model performance using essential evaluation metrics such as accuracy, F1 score, precision, recall, and ROC-AUC.\n",
    "\n",
    "#### 8. XGBoost Feature Importance\n",
    "\n",
    "Visualize the top feature importances from the tuned XGBoost model to understand the most influential factors.\n",
    "\n",
    "### 💻 How to Use\n",
    "\n",
    "1. Clone the Repository.\n",
    "2. Navigate to the Project Directory.\n",
    "3. Explore the Task 2 Notebook.\n",
    "4. Run the Notebook Cells.\n",
    "\n",
    "\n",
    "### 🛠️ Dependencies\n",
    "\n",
    "#### Required Libraries:\n",
    "\n",
    "- Pandas\n",
    "- NumPy\n",
    "- Matplotlib\n",
    "- Plotly\n",
    "- Seaborn\n",
    "- XGBoost\n",
    "- CatBoost\n",
    "- Scikit-learn\n",
    "- Imbalanced-learn\n",
    "- Bayesian optimization (skopt)\n",
    "\n",
    "### 📝 Note\n",
    "\n",
    "Please refrain from directly copying the internship task code for commercial purposes. This repository is for educational purposes only. Use the code wisely and responsibly, and strive to understand the concepts and methodologies behind the analysis.\n",
    "\n",
    "### Performance Metrics of Final Tuned XGBoost Classifier Model\n",
    "\n",
    "| Metric     | On Train Set (%) | On Test Set (%) |\n",
    "|------------|------------------|-----------------|\n",
    "| Accuracy   | 85.346           | 72.435          |\n",
    "| F1         | 86.101           | 71.140          |\n",
    "| Precision  | 81.885           | 74.649          |\n",
    "| Recall     | 90.774           | 67.946          |\n",
    "| ROC_AUC    | 93.499           | 80.286          |\n",
    "\n",
    "### Conclusion\n",
    "\n",
    "Task 2 of the British Airways Internship has unveiled crucial insights into customer booking behavior. Leveraging advanced machine learning techniques, we've identified key factors influencing booking decisions. Our tuned XGBoost model demonstrates high accuracy and precision, equipping British Airways with valuable predictive capabilities.\r\n",
    "\n",
    "---\n",
    "\n",
    "Let's continue our exploration of customer behavior with data-driven insights! ✨🚀"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "",
   "name": ""
  },
  "language_info": {
   "name": ""
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
